# Generated by Django 3.2.7 on 2022-02-07 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('musepost', '0009_auto_20220207_0016'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('like', '좋아요'), ('bookmark', '북마크'), ('comment', '댓글')], max_length=50, verbose_name='알림 카테고리')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='알림 개수')),
                ('is_read', models.BooleanField(default=False, verbose_name='알림 확인 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(db_column='post_idx', on_delete=django.db.models.deletion.CASCADE, related_name='noti', to='musepost.post', verbose_name='알림 게시글')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noti', to=settings.AUTH_USER_MODEL, to_field='user_id', verbose_name='알림 유저')),
            ],
            options={
                'verbose_name_plural': '알림',
                'db_table': 'MUSE_Notification',
            },
        ),
    ]
