# Generated by Django 3.2.7 on 2022-02-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='count',
            field=models.PositiveIntegerField(default=1, verbose_name='알림 개수'),
        ),
    ]
