# Generated by Django 3.2.7 on 2021-09-26 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Topic",
            fields=[
                ("idx", models.AutoField(primary_key=True, serialize=False)),
                ("topic", models.CharField(max_length=128, verbose_name="주제")),
                ("week", models.IntegerField(default=0, verbose_name="해당 주차")),
            ],
            options={
                "db_table": "Topics_of_Site",
            },
        ),
    ]
