# Generated by Django 3.2.7 on 2022-01-06 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=128, verbose_name='주제')),
                ('week', models.IntegerField(default=0, verbose_name='주차')),
                ('activate_week', models.BooleanField(default=False, verbose_name='현재 진행 주차')),
            ],
            options={
                'verbose_name_plural': '콘테스트 주제',
                'db_table': 'MUSE_Topics',
            },
        ),
    ]
