# Generated by Django 3.2.7 on 2021-10-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='activate_week',
            field=models.BooleanField(default=False, verbose_name='현재 진행 주차'),
        ),
    ]
