# Generated by Django 3.2.7 on 2022-03-22 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_auto_20220127_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='생성 날짜'),
        ),
    ]
