# Generated by Django 3.2.7 on 2021-10-29 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_topic_activate_week'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='topic',
            table='Topics',
        ),
    ]
