# Generated by Django 3.2.7 on 2021-11-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0003_alter_topic_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': '콘테스트 주제'},
        ),
        migrations.AlterField(
            model_name='topic',
            name='week',
            field=models.IntegerField(default=0, verbose_name='주차'),
        ),
    ]
