# Generated by Django 3.2.7 on 2021-11-17 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0004_auto_20211117_1129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name_plural': '콘테스트 주제'},
        ),
    ]
