# Generated by Django 3.2.7 on 2021-12-31 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0005_alter_topic_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='topic',
            table='MUSE_Topics',
        ),
    ]
