# Generated by Django 3.2.7 on 2021-12-31 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('banner_main', models.CharField(max_length=1000, verbose_name='배너-메인')),
                ('banner_muse', models.CharField(max_length=1000, verbose_name='배너-뮤즈')),
                ('banner_contest', models.CharField(max_length=1000, verbose_name='배너-콘테스트')),
                ('banner_reference', models.CharField(max_length=1000, verbose_name='배너-레퍼런스')),
                ('tos', models.CharField(max_length=1000, verbose_name='이용 약관')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='최초 업로드 날짜')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='최근 수정 날짜')),
            ],
            options={
                'verbose_name_plural': 'MUSE 공지사항',
                'db_table': 'Notice',
            },
        ),
    ]
