# Generated by Django 3.2.7 on 2021-12-31 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(blank=True, choices=[('main_banner', '메인 배너'), ('muse_banner', '뮤즈 배너'), ('contest_banner', '콘테스트 배너'), ('reference_banner', '레퍼런스 배너')], max_length=30, null=True, verbose_name='배너 카테고리')),
                ('title', models.CharField(blank=True, max_length=1000, null=True, verbose_name='제목')),
                ('content', models.CharField(blank=True, max_length=1000, null=True, verbose_name='내용')),
                ('usage', models.BooleanField(default=True, verbose_name='노출 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='최초 업로드 날짜')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='최근 수정 날짜')),
            ],
            options={
                'verbose_name_plural': '배너',
                'db_table': 'Banner',
            },
        ),
        migrations.AlterModelOptions(
            name='notice',
            options={'verbose_name_plural': '공지사항'},
        ),
        migrations.RemoveField(
            model_name='notice',
            name='banner_contest',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='banner_main',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='banner_muse',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='banner_reference',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='tos',
        ),
        migrations.AddField(
            model_name='notice',
            name='category',
            field=models.CharField(blank=True, choices=[('tos', '이용 약관'), ('guide', '이용 안내'), ('footer', '사이트 설명'), ('one_time', '일회성 팝업')], max_length=30, null=True, verbose_name='공지 카테고리'),
        ),
        migrations.AddField(
            model_name='notice',
            name='content',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='내용'),
        ),
        migrations.AddField(
            model_name='notice',
            name='title',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='제목'),
        ),
        migrations.AddField(
            model_name='notice',
            name='usage',
            field=models.BooleanField(default=True, verbose_name='노출 여부'),
        ),
    ]
