# Generated by Django 3.2.7 on 2021-12-31 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_auto_20211231_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='category',
            field=models.CharField(blank=True, choices=[('tos', '이용 약관'), ('guide', '이용 안내'), ('footer', '사이트 하단 설명'), ('one_time', '일회성 팝업')], max_length=30, null=True, verbose_name='공지 카테고리'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='content',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='title',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='제목'),
        ),
    ]
