# Generated by Django 3.2.7 on 2021-12-31 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0004_auto_20211231_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='category',
            field=models.CharField(blank=True, choices=[('main', '메인 배너'), ('muse', '뮤즈 배너'), ('contest', '콘테스트 배너'), ('reference', '레퍼런스 배너')], max_length=30, null=True, verbose_name='배너 카테고리'),
        ),
    ]
