# Generated by Django 3.2.7 on 2022-01-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0004_alter_notice_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='category',
            field=models.CharField(blank=True, choices=[('tos', '이용 약관'), ('guide', '이용 안내'), ('privacy', '개인정보 처리방침'), ('popup', '일회성 팝업')], max_length=30, null=True, verbose_name='공지 카테고리'),
        ),
    ]
