# Generated by Django 3.2.7 on 2021-12-31 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0005_alter_banner_category'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='banner',
            table='MUSE_Banner',
        ),
        migrations.AlterModelTable(
            name='notice',
            table='MUSE_Notice',
        ),
    ]
