# Generated by Django 3.2.7 on 2021-09-26 06:27

import accounts.models
import common.upload_file
import config.asset_storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("idx", models.AutoField(primary_key=True, serialize=False)),
                (
                    "userid",
                    models.CharField(
                        default="No ID", max_length=128, unique=True, verbose_name="아이디"
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="비밀번호"
                    ),
                ),
                ("username", models.CharField(max_length=45, verbose_name="이름")),
                ("nickname", models.CharField(max_length=45, verbose_name="닉네임")),
                (
                    "date_joined",
                    models.DateTimeField(auto_now_add=True, verbose_name="date joined"),
                ),
                (
                    "last_login",
                    models.DateTimeField(auto_now_add=True, verbose_name="last login"),
                ),
                ("is_superuser", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "User",
            },
            managers=[
                ("objects", accounts.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="accounts.user",
                    ),
                ),
                ("badge", models.IntegerField(default=0)),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        storage=config.asset_storage.PublicMediaStorage(),
                        upload_to=common.upload_file.upload_profile_image,
                    ),
                ),
            ],
            options={
                "db_table": "UserProfile",
            },
        ),
    ]
