# Generated by Django 3.2.7 on 2022-01-11 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='rep_badge',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='score',
            field=models.PositiveIntegerField(default=0, verbose_name='유저 점수'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='badge',
            field=models.PositiveIntegerField(default=0, verbose_name='뱃지 단계'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='instar_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='인스타ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='self_introduce',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='자기 소개'),
        ),
    ]
