# Generated by Django 3.2.7 on 2021-10-07 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_userprofile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="nickname",
            field=models.CharField(max_length=45, unique=True, verbose_name="닉네임"),
        ),
    ]
