# Generated by Django 3.2.7 on 2022-01-12 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220111_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='muse',
            field=models.PositiveIntegerField(default=0, verbose_name='뮤즈 선정 횟수'),
        ),
    ]
