# Generated by Django 3.2.7 on 2021-10-10 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_user_nickname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="userid",
            field=models.CharField(max_length=128, unique=True, verbose_name="아이디"),
        ),
    ]
