# Generated by Django 3.2.7 on 2022-01-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_muse'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tos_agree',
            field=models.BooleanField(default=True, verbose_name='약관 동의 여부'),
        ),
    ]
