# Generated by Django 3.2.7 on 2022-01-25 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_tos_agree'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_first',
            field=models.BooleanField(default=True, verbose_name='첫 로그인 팝업'),
        ),
    ]
