# Generated by Django 3.2.7 on 2021-10-12 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_user_userid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="userid",
            new_name="user_id",
        ),
    ]
