# Generated by Django 3.2.7 on 2022-01-25 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_is_first'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_email',
            field=models.EmailField(blank=True, max_length=150, null=True, unique=True, verbose_name='이메일'),
        ),
    ]
