# Generated by Django 3.2.7 on 2022-01-27 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='instar_id',
            new_name='insta_id',
        ),
    ]
