# Generated by Django 3.2.7 on 2021-10-18 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_follow'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='follow',
            table='UserFollow',
        ),
    ]
