# Generated by Django 3.2.7 on 2021-11-08 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20211103_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='introduce',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='자기소개'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=50, unique=True, verbose_name='닉네임'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(max_length=100, unique=True, verbose_name='아이디'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100, verbose_name='이름'),
        ),
    ]
