# Generated by Django 3.2.7 on 2021-11-08 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20211108_2215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='introduce',
            new_name='self_introduce',
        ),
    ]
