# Generated by Django 3.2.7 on 2021-11-17 11:14

import common.upload_file
import config.asset_storage
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_auto_20211117_1113"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(auto_now_add=True, verbose_name="최초 가입 날짜"),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(auto_now=True, verbose_name="최근 로그인 날짜"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                storage=config.asset_storage.PublicMediaStorage(),
                upload_to=common.upload_file.upload_profile_image,
                verbose_name="프로필 사진",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="badge",
            field=models.IntegerField(default=0, verbose_name="우승 뱃지"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="self_introduce",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="자기 소개"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                db_column="user_id",
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="profile",
                serialize=False,
                to=settings.AUTH_USER_MODEL,
                to_field="user_id",
                verbose_name="유저",
            ),
        ),
    ]
