# Generated by Django 3.2.7 on 2021-12-31 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_userprofile_instar_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='follow',
            table='MUSE_UserFollow',
        ),
        migrations.AlterModelTable(
            name='user',
            table='MUSE_User',
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='MUSE_UserProfile',
        ),
    ]
