# Generated by Django 3.2.7 on 2022-01-03 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20211231_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='badge',
            field=models.IntegerField(default=0, verbose_name='뱃지'),
        ),
    ]
