# Generated by Django 3.2.7 on 2022-01-03 11:14

import common.upload_file
import config.asset_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_userprofile_badge'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='rep_badge',
            field=models.ImageField(blank=True, null=True, storage=config.asset_storage.PublicMediaStorage(), upload_to=common.upload_file.upload_post_image, verbose_name='대표 뱃지'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='badge',
            field=models.IntegerField(default=0, verbose_name='뱃지 개수'),
        ),
    ]
