# Generated by Django 3.2.7 on 2022-01-03 11:44

import common.upload_file
import config.asset_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20220103_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, storage=config.asset_storage.PublicMediaStorage(), upload_to=common.upload_file.upload_profile_image, verbose_name='프로필 사진'),
        ),
    ]
