# Generated by Django 3.2.7 on 2022-01-06 03:35

import common.upload_file
import config.asset_storage
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorOfWeek',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('color1', models.CharField(max_length=50)),
                ('color2', models.CharField(max_length=50)),
                ('color3', models.CharField(max_length=50)),
                ('color4', models.CharField(max_length=50)),
                ('color5', models.CharField(max_length=50)),
                ('cur_status', models.BooleanField(default=True, verbose_name='이번 주 색상')),
            ],
            options={
                'verbose_name_plural': '이번 주 색상',
                'db_table': 'MUSE_ColorOfWeek',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('image', models.ImageField(storage=config.asset_storage.PublicMediaStorage(), upload_to=common.upload_file.upload_post_image, verbose_name='작품')),
                ('content', models.TextField(max_length=1000, verbose_name='내용')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='좋아요')),
                ('topic', models.CharField(blank=True, max_length=128, null=True, verbose_name='주제')),
                ('week', models.IntegerField(blank=True, default=0, null=True, verbose_name='해당 주차')),
                ('ref_url', models.CharField(blank=True, max_length=256, null=True, verbose_name='원본 URL')),
                ('dominant_color', models.CharField(blank=True, max_length=50, null=True, verbose_name='지배 색상')),
                ('palette_color1', models.CharField(blank=True, max_length=50, null=True, verbose_name='유사 색상1')),
                ('palette_color2', models.CharField(blank=True, max_length=50, null=True, verbose_name='유사 색상2')),
                ('palette_color3', models.CharField(blank=True, max_length=50, null=True, verbose_name='유사 색상3')),
                ('category', models.CharField(blank=True, choices=[('contest', '콘테스트'), ('reference', '레퍼런스')], max_length=30, null=True, verbose_name='게시물 카테고리')),
                ('cur_status', models.BooleanField(default=True, verbose_name='이번 주 게시물')),
                ('is_muse', models.BooleanField(default=False, verbose_name='MUSE 선정 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='최초 업로드 날짜')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='최근 수정 날짜')),
                ('hashtag', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to=settings.AUTH_USER_MODEL, to_field='user_id', verbose_name='작성자')),
            ],
            options={
                'verbose_name_plural': '게시글',
                'db_table': 'MUSE_Post',
            },
        ),
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('like_user', models.ForeignKey(db_column='like_user', default='default', on_delete=django.db.models.deletion.CASCADE, related_name='likeUser', to=settings.AUTH_USER_MODEL, to_field='user_id', verbose_name='좋아요 누른 유저')),
                ('post', models.ForeignKey(db_column='post_idx', on_delete=django.db.models.deletion.CASCADE, related_name='post_like', to='musepost.post', verbose_name='게시글')),
            ],
            options={
                'verbose_name_plural': '게시글 좋아요',
                'db_table': 'MUSE_Post_Like',
            },
        ),
        migrations.CreateModel(
            name='PostBookmark',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(db_column='post_idx', on_delete=django.db.models.deletion.CASCADE, related_name='post_bookmark', to='musepost.post', verbose_name='게시글 북마크')),
                ('user', models.ForeignKey(db_column='user_bookmark', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='user_id', verbose_name='유저 북마크')),
            ],
            options={
                'verbose_name_plural': '게시글 북마크',
                'db_table': 'MUSE_Post_Bookmark',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.CharField(default='None', max_length=100, verbose_name='댓글')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='최초 업로드 날짜')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='최근 수정 날짜')),
                ('post', models.ForeignKey(db_column='post_idx', on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='musepost.post', verbose_name='게시글')),
                ('writer', models.ForeignKey(db_column='writer_id', on_delete=django.db.models.deletion.CASCADE, related_name='comment', to=settings.AUTH_USER_MODEL, to_field='user_id', verbose_name='작성자')),
            ],
            options={
                'verbose_name_plural': '댓글',
                'db_table': 'MUSE_Post_Comments',
            },
        ),
    ]
