# Generated by Django 3.2.7 on 2021-10-10 05:38

import config.asset_storage
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import common.upload_file


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                ("idx", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100, verbose_name="제목")),
                (
                    "body_image",
                    models.ImageField(
                        storage=config.asset_storage.PublicMediaStorage(),
                        upload_to=common.upload_file.upload_post_image,
                        verbose_name="작품",
                    ),
                ),
                ("body_text", models.TextField(max_length=300, verbose_name="내용")),
                ("hits", models.IntegerField(default=0, verbose_name="조회수")),
                ("liked", models.IntegerField(default=0, verbose_name="좋아요")),
                (
                    "topic",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="주제"
                    ),
                ),
                (
                    "week",
                    models.IntegerField(
                        blank=True, default=0, null=True, verbose_name="해당 주차"
                    ),
                ),
                (
                    "cur_status",
                    models.BooleanField(default=True, verbose_name="현재 진행 여부"),
                ),
                (
                    "is_muse",
                    models.BooleanField(default=False, verbose_name="MUSE 선정 여부"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="최초 업로드 날짜"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="최근 수정 날짜"),
                ),
                (
                    "writer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="writer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "Post",
            },
        ),
        migrations.CreateModel(
            name="PostLike",
            fields=[
                ("idx", models.AutoField(primary_key=True, serialize=False)),
                (
                    "like_user",
                    models.ForeignKey(
                        db_column="post_like_user",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likeUser",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        db_column="post_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likePost",
                        to="musepost.post",
                    ),
                ),
            ],
            options={
                "db_table": "Post_Like",
            },
        ),
        migrations.CreateModel(
            name="Hashtag",
            fields=[
                ("idx", models.AutoField(primary_key=True, serialize=False)),
                ("hashtag1", models.CharField(max_length=32, verbose_name="해시태그_1")),
                ("hashtag2", models.CharField(max_length=32, verbose_name="해시태그_2")),
                ("hashtag3", models.CharField(max_length=32, verbose_name="해시태그_3")),
                (
                    "post",
                    models.ForeignKey(
                        db_column="post_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hashtag",
                        to="musepost.post",
                    ),
                ),
            ],
            options={
                "db_table": "Post_Hashtag",
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("idx", models.AutoField(primary_key=True, serialize=False)),
                (
                    "comment",
                    models.CharField(default="None", max_length=128, verbose_name="댓글"),
                ),
                (
                    "comment_writer",
                    models.ForeignKey(
                        db_column="comment_writer",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="commentWriter",
                        to=settings.AUTH_USER_MODEL,
                        to_field="nickname",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        db_column="post_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment",
                        to="musepost.post",
                    ),
                ),
            ],
            options={
                "db_table": "Post_Comments",
            },
        ),
    ]
