# Generated by Django 3.2.7 on 2022-01-18 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musepost', '0002_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='usage',
            field=models.BooleanField(default=True, verbose_name='노출 여부'),
        ),
    ]
