# Generated by Django 3.2.7 on 2021-10-10 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("musepost", "0002_alter_post_writer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postlike",
            name="like_user",
            field=models.ForeignKey(
                db_column="post_like_user",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likeUser",
                to=settings.AUTH_USER_MODEL,
                to_field="userid",
            ),
        ),
    ]
