# Generated by Django 3.2.7 on 2022-01-30 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musepost', '0003_post_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorofweek',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
