# Generated by Django 3.2.7 on 2021-10-10 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("musepost", "0004_alter_postlike_like_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                db_column="post_idx",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comment",
                to="musepost.post",
            ),
        ),
        migrations.AlterField(
            model_name="postlike",
            name="like_user",
            field=models.ForeignKey(
                db_column="like_user",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likeUser",
                to=settings.AUTH_USER_MODEL,
                to_field="nickname",
            ),
        ),
        migrations.AlterField(
            model_name="postlike",
            name="post",
            field=models.ForeignKey(
                db_column="post_idx",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likePost",
                to="musepost.post",
            ),
        ),
    ]
