# Generated by Django 3.2.7 on 2022-01-30 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musepost', '0004_colorofweek_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorofweek',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
