# Generated by Django 3.2.7 on 2021-10-10 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("musepost", "0005_auto_20211010_1611"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hashtag",
            name="post",
            field=models.ForeignKey(
                db_column="post_idx",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hashtag",
                to="musepost.post",
            ),
        ),
    ]
