# Generated by Django 3.2.7 on 2022-02-04 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musepost', '0005_alter_colorofweek_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(default='None', max_length=1000, verbose_name='댓글'),
        ),
    ]
