# Generated by Django 3.2.7 on 2022-02-04 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musepost', '0006_alter_comment_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorofweek',
            name='color1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='colorofweek',
            name='color2',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='colorofweek',
            name='color3',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='colorofweek',
            name='color4',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='colorofweek',
            name='color5',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, choices=[('contest', '콘테스트'), ('reference', '레퍼런스')], max_length=50, null=True, verbose_name='게시물 카테고리'),
        ),
        migrations.AlterField(
            model_name='post',
            name='dominant_color',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='지배 색상'),
        ),
        migrations.AlterField(
            model_name='post',
            name='palette_color1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='유사 색상1'),
        ),
        migrations.AlterField(
            model_name='post',
            name='palette_color2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='유사 색상2'),
        ),
        migrations.AlterField(
            model_name='post',
            name='palette_color3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='유사 색상3'),
        ),
        migrations.AlterField(
            model_name='post',
            name='ref_url',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='원본 URL'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, verbose_name='제목'),
        ),
        migrations.AlterField(
            model_name='post',
            name='topic',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='주제'),
        ),
    ]
