# Generated by Django 3.2.7 on 2022-02-06 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musepost', '0007_auto_20220204_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_extract_color',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PostColor',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('palette_color1', models.CharField(blank=True, max_length=100, null=True, verbose_name='색상1')),
                ('palette_color2', models.CharField(blank=True, max_length=100, null=True, verbose_name='색상2')),
                ('palette_color3', models.CharField(blank=True, max_length=100, null=True, verbose_name='색상3')),
                ('palette_color4', models.CharField(blank=True, max_length=100, null=True, verbose_name='색상4')),
                ('palette_color5', models.CharField(blank=True, max_length=100, null=True, verbose_name='색상5')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(db_column='post_idx', on_delete=django.db.models.deletion.CASCADE, related_name='post_color', to='musepost.post', verbose_name='게시글')),
            ],
            options={
                'verbose_name_plural': '게시글 색상',
                'db_table': 'MUSE_PostColor',
            },
        ),
    ]
