# Generated by Django 3.2.7 on 2021-10-10 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("musepost", "0008_alter_post_tags"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Hashtag",
        ),
    ]
