# Generated by Django 3.2.7 on 2022-02-07 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musepost', '0008_auto_20220206_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='dominant_color',
        ),
        migrations.RemoveField(
            model_name='post',
            name='palette_color1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='palette_color2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='palette_color3',
        ),
        migrations.AlterModelTable(
            name='postcolor',
            table='MUSE_Post_Color',
        ),
    ]
