# Generated by Django 3.2.7 on 2022-03-22 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musepost', '0009_auto_20220207_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorofweek',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성 날짜'),
        ),
    ]
