# Generated by Django 3.2.7 on 2021-10-11 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("musepost", "0010_alter_comment_comment_writer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="comment_writer",
            field=models.ForeignKey(
                db_column="comment_writer",
                default="다람쥐",
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="commentWriter",
                to=settings.AUTH_USER_MODEL,
                to_field="nickname",
            ),
        ),
    ]
