# Generated by Django 3.2.7 on 2022-04-15 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musepost', '0013_alter_post_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='thumbnail',
        ),
    ]
