# Generated by Django 3.2.7 on 2022-04-15 01:37

import common.upload_file
import config.asset_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musepost', '0014_remove_post_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, storage=config.asset_storage.PublicMediaStorage(), upload_to=common.upload_file.upload_thumbnail_image, verbose_name='썸네일'),
        ),
    ]
