# Generated by Django 3.2.7 on 2022-04-15 02:01

import common.upload_file
import config.asset_storage
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('musepost', '0015_post_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, size=[640, 480], storage=config.asset_storage.PublicMediaStorage(), upload_to=common.upload_file.upload_thumbnail_image, verbose_name='썸네일'),
        ),
    ]
