# Generated by Django 3.2.7 on 2021-10-11 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("musepost", "0020_auto_20211011_1834"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="comment_writer",
            field=models.ForeignKey(
                db_column="comment_writer",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commentWriter",
                to="accounts.user",
                to_field="userid",
            ),
        ),
        migrations.AlterField(
            model_name="postlike",
            name="like_user",
            field=models.ForeignKey(
                db_column="like_user",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likeUser",
                to="accounts.user",
                to_field="userid",
            ),
        ),
    ]
