# Generated by Django 3.2.7 on 2021-10-12 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("musepost", "0022_auto_20211012_2305"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="writer",
            field=models.ForeignKey(
                db_column="comment_writer",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commentWriter",
                to=settings.AUTH_USER_MODEL,
                to_field="user_id",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="writer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="writer",
                to=settings.AUTH_USER_MODEL,
                to_field="user_id",
            ),
        ),
        migrations.AlterField(
            model_name="postlike",
            name="like_user",
            field=models.ForeignKey(
                db_column="like_user",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likeUser",
                to=settings.AUTH_USER_MODEL,
                to_field="user_id",
            ),
        ),
    ]
