# Generated by Django 3.2.7 on 2021-10-13 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("musepost", "0024_auto_20211013_0325"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="views",
            field=models.PositiveIntegerField(default=0, verbose_name="조회수"),
        ),
    ]
