# Generated by Django 3.2.7 on 2021-10-14 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musepost', '0026_auto_20211013_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.PositiveIntegerField(default=0, verbose_name='좋아요'),
        ),
    ]
