# Generated by Django 3.2.7 on 2021-10-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musepost', '0027_alter_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='최근 수정 날짜'),
        ),
    ]
