# Generated by Django 3.2.7 on 2021-10-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musepost', '0028_alter_post_modified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='최근 수정 날짜'),
        ),
    ]
