# Generated by Django 3.2.7 on 2021-10-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musepost', '0029_alter_comment_modified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_contest',
            field=models.BooleanField(default=False, verbose_name='콘테스트 참가 여부'),
        ),
        migrations.AlterField(
            model_name='post',
            name='cur_status',
            field=models.BooleanField(default=False, verbose_name='현재 진행 여부'),
        ),
    ]
