# Generated by Django 3.2.7 on 2021-10-29 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musepost', '0030_auto_20211016_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_contest',
            field=models.BooleanField(default=True, verbose_name='콘테스트 참가 여부'),
        ),
    ]
