# Generated by Django 3.2.7 on 2021-10-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musepost', '0031_alter_post_is_contest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cur_status',
            field=models.BooleanField(default=True, verbose_name='현재 진행 여부'),
        ),
    ]
