# Generated by Django 3.2.7 on 2021-11-17 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('musepost', '0032_alter_post_cur_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '댓글'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': '게시글'},
        ),
        migrations.AlterModelOptions(
            name='postlike',
            options={'verbose_name': '게시글 Like'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(db_column='post_idx', on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='musepost.post', verbose_name='게시글'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='writer',
            field=models.ForeignKey(db_column='writer_id', on_delete=django.db.models.deletion.CASCADE, related_name='comment', to=settings.AUTH_USER_MODEL, to_field='user_id', verbose_name='작성자'),
        ),
        migrations.AlterField(
            model_name='post',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to=settings.AUTH_USER_MODEL, to_field='user_id', verbose_name='작성자'),
        ),
        migrations.AlterField(
            model_name='postlike',
            name='like_user',
            field=models.ForeignKey(db_column='like_user', on_delete=django.db.models.deletion.CASCADE, related_name='likeUser', to=settings.AUTH_USER_MODEL, to_field='user_id', verbose_name='좋아요 누른 유저'),
        ),
        migrations.AlterField(
            model_name='postlike',
            name='post',
            field=models.ForeignKey(db_column='post_idx', on_delete=django.db.models.deletion.CASCADE, related_name='post_like', to='musepost.post', verbose_name='게시글'),
        ),
    ]
