# Generated by Django 3.2.7 on 2021-11-17 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musepost', '0033_auto_20211117_1129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name_plural': '댓글'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name_plural': '게시글'},
        ),
        migrations.AlterModelOptions(
            name='postlike',
            options={'verbose_name_plural': '게시글 좋아요'},
        ),
    ]
