# Generated by Django 3.2.7 on 2021-12-07 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musepost', '0034_auto_20211117_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ref_url',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='원본 URL'),
        ),
    ]
