# Generated by Django 3.2.7 on 2021-12-14 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musepost', '0036_auto_20211214_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_reference',
            field=models.BooleanField(default=False, verbose_name='레퍼런스 게시물'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_contest',
            field=models.BooleanField(default=True, verbose_name='콘테스트 게시물'),
        ),
    ]
