# Generated by Django 3.2.7 on 2021-12-28 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("musepost", "0037_auto_20211214_1605"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostBookmark",
            fields=[
                ("idx", models.AutoField(primary_key=True, serialize=False)),
                (
                    "post",
                    models.ForeignKey(
                        db_column="post_idx",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_bookmark",
                        to="musepost.post",
                        verbose_name="게시글 북마크",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_bookmark",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        to_field="user_id",
                        verbose_name="유저 북마크",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "게시글 북마크",
                "db_table": "Post_Bookmark",
            },
        ),
    ]
