# Generated by Django 3.2.7 on 2021-12-28 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musepost', '0039_alter_postlike_like_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostLike',
        ),
    ]
