# Generated by Django 3.2.7 on 2021-12-28 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('musepost', '0040_delete_postlike'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('like_user', models.ForeignKey(db_column='like_user', default='default', on_delete=django.db.models.deletion.CASCADE, related_name='likeUser', to=settings.AUTH_USER_MODEL, to_field='user_id', verbose_name='좋아요 누른 유저')),
                ('post', models.ForeignKey(db_column='post_idx', on_delete=django.db.models.deletion.CASCADE, related_name='post_like', to='musepost.post', verbose_name='게시글')),
            ],
            options={
                'verbose_name_plural': '게시글 좋아요',
                'db_table': 'Post_Like',
            },
        ),
    ]
