# Generated by Django 3.2.7 on 2021-12-31 14:02

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('musepost', '0041_postlike'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name_plural': '해시태그',
                'db_table': 'Tag',
            },
        ),
        migrations.CreateModel(
            name='TaggedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musepost.post')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='musepost_taggedpost_items', to='taggit.tag')),
                ('tags', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tagged_post', to='musepost.tag')),
            ],
            options={
                'verbose_name_plural': '해시태그-게시글',
                'db_table': 'TaggedPost',
            },
        ),
        migrations.AlterField(
            model_name='post',
            name='hashtag',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='musepost.TaggedPost', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
