# Generated by Django 3.2.7 on 2021-12-31 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musepost', '0044_auto_20211231_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dominant_color',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='지배 색상'),
        ),
        migrations.AddField(
            model_name='post',
            name='palette_color1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='유사 색상1'),
        ),
        migrations.AddField(
            model_name='post',
            name='palette_color2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='유사 색상2'),
        ),
        migrations.AddField(
            model_name='post',
            name='palette_color3',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='유사 색상3'),
        ),
    ]
