# Generated by Django 3.2.7 on 2022-01-02 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musepost', '0046_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_contest',
        ),
        migrations.RemoveField(
            model_name='post',
            name='is_reference',
        ),
    ]
