# Generated by Django 3.2.7 on 2022-01-03 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musepost', '0047_auto_20220102_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cur_status',
            field=models.BooleanField(default=False, verbose_name='현재 진행 여부'),
        ),
    ]
