# Generated by Django 3.2.7 on 2022-01-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musepost', '0048_alter_post_cur_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cur_status',
            field=models.BooleanField(default=True, verbose_name='이번 주 게시물'),
        ),
    ]
