# Generated by Django 3.2.7 on 2022-01-03 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musepost', '0050_auto_20220103_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorOfWeek',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('color1', models.CharField(max_length=50)),
                ('color2', models.CharField(max_length=50)),
                ('color3', models.CharField(max_length=50)),
                ('color4', models.CharField(max_length=50)),
                ('color5', models.CharField(max_length=50)),
                ('cur_status', models.BooleanField(default=True, verbose_name='이번 주 색상')),
            ],
            options={
                'verbose_name_plural': '이번 주 색상',
                'db_table': 'MUSE_ColorOfWeek',
            },
        ),
        migrations.AlterField(
            model_name='post',
            name='dominant_color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='지배 색상'),
        ),
        migrations.AlterField(
            model_name='post',
            name='palette_color1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='유사 색상1'),
        ),
        migrations.AlterField(
            model_name='post',
            name='palette_color2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='유사 색상2'),
        ),
        migrations.AlterField(
            model_name='post',
            name='palette_color3',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='유사 색상3'),
        ),
    ]
